package cmd

import (
	"context"
	"os"

	"github.com/charmbracelet/fang"
	"github.com/spf13/cobra"
	"wslp/internal/config"
)

// RootCmd represents the base command when called without any subcommands
var RootCmd = &cobra.Command{
	Use:   "wslp",
	Short: "A tool for managing WSL instances.",
	Long:  `Create, delete, and rename instances. Perform bulk actions on multiple instances.`,

	// Avoid the "Auto generated by spf13/cobra" line in the generated markdown docs
	DisableAutoGenTag: true,
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	if err := fang.Execute(context.Background(), RootCmd); err != nil {
		os.Exit(1)
	}
}

func init() {
	// Initialize configuration
	config.Init()
}
